# Generated by Django 4.2.4 on 2023-08-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_can_be_contacted_bool_user_can_data_be_shared"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="can_be_contacted_bool",
        ),
        migrations.RemoveField(
            model_name="user",
            name="can_data_be_shared_bool",
        ),
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="can_be_contacted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_data_be_shared",
            field=models.BooleanField(default=False),
        ),
    ]
